version: "3.3"
# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/#gunicorn

services:
  db-postgres:
    image: postgres
    restart: unless-stopped
    container_name: my_project-db
    environment:
      - POSTGRES_DB=psql-db
      - POSTGRES_USER=psql-user
      - POSTGRES_PASSWORD=psql-pass

  django-compose:
    build: .
    container_name: my_project-app
    ports:
      - "8000:8000"
    depends_on:
      - db-postgres
    environment:
      - DJANGO_SETTINGS_MODULE=my_project.settings.docker_dev
      - DJANGO_SECRET_KEY=abcdefghijklmnopqrstuvwxyz0123456789!@%^&*(-_=+)50
      - DJANGO_DEBUG=True
      - REST_SIGNING_KEY=rest-top-secret
      - DATABASE_URL=postgresql://psql-user:psql-pass@db-postgres:5432/psql-db
